Repository GSG-CF05/Delivery-App-team1, pull requests merged in 2022-02, with the labels that each got.

#4 Create the file structure
  checkout/checkout.css
  checkout/checkout.html
  index.html
  productDetails/productDetails.css
  productDetails/productDetails.html
  style.css
  yourOrders/order.css
  yourOrders/order.html
Labels: waiting-review

#11 create a checkout page
  checkout/checkout.css
  checkout/checkout.html
  checkout/icons/Add Card.svg
  checkout/icons/Chevron Left.svg
  checkout/icons/Icons.svg
  checkout/icons/Navigation.svg
  checkout/icons/Path.svg
  checkout/icons/PayPal.svg
  checkout/icons/Time.svg
  checkout/icons/Visa.svg
Labels: awaiting-review

#19 create the order page
  .vscode/settings.json
  Images/coffe1.png
  Images/coffe2.png
  Images/coffe3.png
  yourOrders/order.css
  yourOrders/order.html
Labels: awaiting-review

#7 creating and adding the details to the readme file
  README.md
Labels: in-progress

#29 making the order page responsive
  yourOrders/order.css
  yourOrders/order.html
Labels: awaiting-review

#10 create tabs
  index.html
  style.css
Labels: approve
